const NOT_FOUND_ERROR = 404;
const SERVER_ERROR = 500;
const INVALID_DATA = 400;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;

module.exports  = {
  NOT_FOUND_ERROR,
  SERVER_ERROR,
  INVALID_DATA,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR
}